#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     leftdrive,     tmotorTetrix, PIDControl, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     rightdrive,    tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C2_1,     ballraiser,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     ballgrabber,   tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    grabber,              tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

int transfer_J_To_M(int joy,float slope,int dead) // joy = joy input, dead = dead band, slope = max motor output/max joy input - in this case 100/128
{
    int y;
    if (abs(joy)<dead)
        y=0;
    else
        y=slope*((float)joy-(float)dead*sgn(joy));

    return y;
}

task main
{
	//int threshold = 20; // The absolute value of the threshold below which the joysticks will not move
	//bool grabber_down=false;
	int joy_1x1;
  int joy_1x2;
  int joy_1y1;
  int joy_1y2;
  int tophat;
  int joy_2x1;
  int joy_2x2;
  int joy_2y1;
  int joy_2y2;
  float joyslope=100./128.;
  int dband=20;
  waitForStart();
  //motor[ballgrabber]=50;
	while (true)
	{
		getJoystickSettings(joystick);

		joy_1y1=transfer_J_To_M(-joystick.joy1_y1, joyslope*(float)1/8, dband);
    joy_1y2=transfer_J_To_M(-joystick.joy1_y2, joyslope*(float)1/8, dband);
    joy_1x1=transfer_J_To_M(joystick.joy1_x1, joyslope, dband);
    joy_1x2=transfer_J_To_M(joystick.joy1_x2, joyslope, dband);
    tophat=joystick.joy1_TopHat;
    joy_2y1=transfer_J_To_M(-joystick.joy2_y1, joyslope, dband);
    joy_2y2=transfer_J_To_M(-joystick.joy2_y2, joyslope, dband);
    joy_2x1=transfer_J_To_M(joystick.joy2_x1, joyslope, dband);
    joy_2x2=transfer_J_To_M(joystick.joy2_x2, joyslope, dband);

    /*
		writeDebugStreamLine( "%4d ,%4d ,%4d"
		, joy_1y1 // Left Track
		, joy_1y2 // Right Track
		, joy_2y1 // Raise tower
		);
		*/

		motor[ballraiser]=joy_2y2;//if joy_2y2 is below deadband motor will not move
		motor[rightdrive]=joy_1y1;
		motor[leftdrive]=joy_1y2;

		//writeDebugStreamLine("%d   %d", tophat , (int)1 * grabber_down);
	//writeDebugStreamLine("Grabber pos: %d", servo[grabber]);
	/*if (!grabber_down){//is down (equals to true)
				writeDebugStreamLine("grabber up");
	}

	servo[grabber]=129;//EDIT PLZ

	if (tophat==4){
			if (!grabber_down){//is down (equals to true)
				writeDebugStreamLine("grabber is moving up");
				servo[grabber]=120;//EDIT PLZ
				grabber_down=true;
			}

		if (tophat==0){
				if (grabber_down){
					writeDebugStreamLine("grabber is moving down");
					servo[grabber]=130;
					grabber_down=false;
				}
			}

		}
		*/

	}
}
