#pragma config(Sensor, S1,     accel,          sensorI2CCustom)
#pragma config(Motor,  motorA,          left,          tmotorNXT, PIDControl, reversed, driveLeft, encoder)
#pragma config(Motor,  motorB,          right,         tmotorNXT, PIDControl, reversed, driveRight, encoder)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//motor[left] is the master and the slave it motor[right]
#include "hitechnic-accelerometer.h"

//Timers Used: T1 (change Rate),
void init(){
	//Motors//
	nSyncedMotors = synchAB;
	nSyncedTurnRatio = 100;//the same as the master (100%)
}

task main()
{
	int accelOffSet = 40;
	int multiplyer = 100;
	float delta;
	int x;
	int y;
	int z;
	int motorOutput;
	init();
	// ClearTimer(T1);


	while (true){
		//wait1Msec(1);
		HTACreadAllAxes(accel, x, y, z);
		delta = (x+accelOffSet);
		motorOutput = round(multiplyer*delta);

		if(0){
		nxtDisplayCenteredTextLine(2,"delta: %f",delta);
		nxtDisplayCenteredTextLine(5,"motorOutput: %d",motorOutput);
		nxtDisplayCenteredTextLine(6,"value: %d",x);
		}

		motor[left] = round(multiplyer*delta);
	}

	}
