#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     leftdrive,     tmotorTetrix, PIDControl, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     rightdrive,    tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C2_1,     ballraiser,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     ballgrabber,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorH,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    bottle_angle,         tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    cm_extension,         tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "hitechnic-irseeker-v2.h"
#include "JoystickDriver.c"

task main
{
	waitForStart();
	int threshold = 20; // The absolute value of the threshold below which the joysticks will not move
	while (true)
	{
		getJoystickSettings(joystick);

		motor[ballgrabber] = 50;

		if(abs(joystick.joy1_y1) > threshold)     ////////////
		{                                         //
			motor[leftdrive] = joystick.joy1_y1;    // Sometimes, the joysticks' default position isn't always zero;
		}                                         // this code accounts for that by creating a "Dead zone", where
		else                                      // if the joysticks' position is less than 20 or greater than -20,
		{                                         // the motors don't run.
			motor[leftdrive] = 0;                   //
		}                                         ////////////


		if(abs(joystick.joy1_y2) > threshold)
		{
			motor[rightdrive] = joystick.joy1_y2;
		}
		else
		{
			motor[rightdrive] = 0;
		}

		if (joy1btn(00)==1){
			if (grabber_down){//is down (equals to true)
				servo[grabber]=;//EDIT PLZ
			}
			else{
				servo[grabber]=0;
			}
		}
	}
}
