#pragma config(Sensor, S1,     MSMMUX,              sensorI2CCustomFastSkipStates)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#define sonarF S4//set the sensor plugged into passthrough to the same port

#include "mindsensors-motormux.h"
#include "lego-ultrasound.h"

task main()
{
	MSMMUXinit();
	MSMotorStop(mmotor_S1_1);
  MSMotorStop(mmotor_S1_2);
	//int feedBack;
	MSMMotor(mmotor_S1_1, 15);
	wait1Msec(1000);
	MSMotorStop(mmotor_S1_1);
}
