#pragma config(Sensor, S4,     us,             sensorSONAR)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "mindsensors-motormux.h"

task main()
{
	while (true){
		nxtDisplayCenteredBigTextLine(3,"%d",SensorValue[us]);
	}
}
