#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CHiTechnicCompass)
#pragma config(Motor,  motorA,          unused1,       tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          unused2,       tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          unused3,       tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     arm1,          tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     arm2,          tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     FLeft,         tmotorTetrix, openLoop, driveLeft)
#pragma config(Motor,  mtr_S1_C2_2,     BLeft,         tmotorTetrix, openLoop, driveLeft)
#pragma config(Motor,  mtr_S1_C3_1,     FRight,        tmotorTetrix, openLoop, reversed, driveRight)
#pragma config(Motor,  mtr_S1_C3_2,     BRight,        tmotorTetrix, openLoop, reversed, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

#include "Transfer.c"

task main()
{
	/*Motor map:

	Motor Controller 1 = arm motors(not called in)
	Motor Controller 2 = left motor 1 & 2, spliced
	                     left motor 3
	Motor Controller 3 = right motor 1 & 2, spliced
	                     right motor 3*/

	int dband = 10;

	int joy_1y1=transfer_J_To_M(joystick.joy1_y1,100./320.,dband);
	int joy_1y2=transfer_J_To_M(joystick.joy1_y2,100./320.,dband);
	int joy_2y1=transfer_J_To_M(joystick.joy2_y1,100./320.,dband);
	int joy_2y2=transfer_J_To_M(joystick.joy2_y2,100./320.,dband);

	while (true)
	{
		getJoystickSettings(joystick);
		joy_1y1=transfer_J_To_M(joystick.joy1_y1,100./320.,dband);
		joy_1y2=transfer_J_To_M(joystick.joy1_y2,100./320.,dband);
		joy_2y1=transfer_J_To_M(joystick.joy2_y1,100./320.,dband);
		joy_2y2=transfer_J_To_M(joystick.joy2_y2,100./320.,dband);

		//nxtDisplayCenteredBigTextLine(3,"%d",motor[FRight]);

		//nxtDisplayCenteredBigTextLine(6,"%d",joystick.joy1_y1);
		writeDebugStreamLine("Mid: %d, Back:%d",nMotorEncoder[FRight],nMotorEncoder[BRight]);
		motor[FLeft]=joy_1y1;
		motor[BLeft]=joy_1y1;
		motor[FRight]=joy_1y2;
		motor[BRight]=joy_1y2;
		//motor[arm1]=joy_2y1;
		motor[arm2]=joy_2y1;
	}
}
