#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     rightF,        tmotorTetrix, openLoop, driveRight)
#pragma config(Motor,  mtr_S1_C1_2,     rightB,        tmotorTetrix, openLoop, driveRight)
#pragma config(Motor,  mtr_S1_C2_1,     leftF,         tmotorTetrix, openLoop, reversed, driveLeft)
#pragma config(Motor,  mtr_S1_C2_2,     leftB,         tmotorTetrix, openLoop, reversed, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int speed=20;
	motor[rightF]=speed;
	motor[rightB]=speed;
	motor[leftF]=speed;
	motor[leftB]=speed;
	wait1Msec(5000);
}
