#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     arm,           tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     leftfront,     tmotorTetrix, openLoop, driveLeft)
#pragma config(Motor,  mtr_S1_C2_2,     leftback,      tmotorTetrix, openLoop, driveLeft)
#pragma config(Motor,  mtr_S1_C3_1,     rightfront,    tmotorTetrix, openLoop, reversed, driveRight)
#pragma config(Motor,  mtr_S1_C3_2,     rightback,     tmotorTetrix, openLoop, reversed, driveRight)
#pragma config(Servo,  srvo_S1_C4_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int fwdpower = 30;
	int rampdist = 450;

	while (nMotorEncoderTarget[leftback] < rampdist || nMotorEncoderTarget[rightback] < rampdist)
{
	motor[leftfront] = fwdpower;
	motor[leftback] = fwdpower;
	motor[rightfront] = fwdpower;
	motor[rightback] = fwdpower;
}
  motor[leftfront] = 0;
	motor[leftback] = 0;
	motor[rightfront] = 0;
	motor[rightback] = 0;
	/*if (nMotorEncoderTarget[leftback] < rampdist || nMotorEncoderTarget[rightback] < rampdist)
{
	motor[leftfront] = fwdpower;
	motor[leftback] = fwdpower;
	motor[rightfront] = fwdpower;
	motor[rightback] = fwdpower;
}
	else
{
	motor[leftfront] = 0;
	motor[leftback] = 0;
	motor[rightfront] = 0;
	motor[rightback] = 0;
} */
}
//}
