#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CHiTechnicCompass)
#pragma config(Motor,  motorA,          arm2,          tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          unused2,       tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          unused3,       tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     arm1,          tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     cheese,        tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     FLeft,         tmotorTetrix, openLoop, driveLeft)
#pragma config(Motor,  mtr_S1_C2_2,     BLeft,         tmotorTetrix, openLoop, driveLeft)
#pragma config(Motor,  mtr_S1_C3_1,     FRight,        tmotorTetrix, openLoop, reversed, driveRight)
#pragma config(Motor,  mtr_S1_C3_2,     BRight,        tmotorTetrix, openLoop, reversed, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "Transfer.c"

int begpos=0;
int joylevels[4]={0,30,50,100};
int moveamount=0;
int dband = 10;
int joy_2y1=transfer_J_To_M(joystick.joy2_y1,100./2560.,dband);
int joy_2y2=transfer_J_To_M(joystick.joy2_y2,100./2560.,dband);
int armspeed=10;

task armmove(){
	clearTimer(T1);
	while (true)
	{
		if (time100[T1]>5)
		{
			moveamount=nMotorEncoder[arm2];
			for (int ii=0; ii<sizeof(joylevels)/4; ii++)
			{
				if (ii==joylevels[0]){
					break;
				}
				else if (ii>=(sizeof(joylevels)/4)-1){
					moveamount=moveamount+(sizeof(joylevels)/4)-1;
					break;
				}
				else if (abs(joy_2y1)>joylevels[ii] && abs(joy_2y1)<joylevels[ii+1]){
					if (sgn(joy_2y1)==1){//is forward
						moveamount=moveamount+ii;
					}
					else if (sgn(joy_2y1)==-1){
						moveamount=moveamount-ii;
					}
					break;
				}
			}

			//MOVEMENT

			while (nMotorEncoder[arm2]!=moveamount){
				if (nMotorEncoder[arm2]<moveamount){
					motor[arm2]=armspeed;
				}
				else if (nMotorEncoder[arm2]>moveamount){
					motor[arm2]=-armspeed;
				}
			}
			clearTimer(T1);
		}
	}
}

task main()
{
	/*Motor map:

	Motor Controller 1 = arm motors(not called in)
	Motor Controller 2 = left motor 1 & 2, spliced
	left motor 3
	Motor Controller 3 = right motor 1 & 2, spliced
	right motor 3*/
	startTask(armmove);
	int joy_1y1=transfer_J_To_M(joystick.joy1_y1,100./320.,dband);
	int joy_1y2=transfer_J_To_M(joystick.joy1_y2,100./320.,dband);

	while (true)
	{
		getJoystickSettings(joystick);
		joy_1y1=transfer_J_To_M(joystick.joy1_y1,100./320.,dband);
		joy_1y2=transfer_J_To_M(joystick.joy1_y2,100./320.,dband);
		joy_2y1=transfer_J_To_M(joystick.joy2_y1,100./2560.,dband);
		joy_2y2=transfer_J_To_M(joystick.joy2_y2,100./2560.,dband);

		//nxtDisplayCenteredBigTextLine(3,"%d",motor[FRight]);

		//nxtDisplayCenteredBigTextLine(6,"%d",joystick.joy1_y1);
		writeDebugStreamLine("Mid: %d, Back:%d",nMotorEncoder[FRight],nMotorEncoder[BRight]);
		motor[FLeft]=joy_1y1;
		motor[BLeft]=joy_1y1;
		motor[FRight]=joy_1y2;
		motor[BRight]=joy_1y2;


	}
}
