#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     rightF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     rightB,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     leftF,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     leftB,         tmotorTetrix, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	bFloatDuringInactiveMotorPWM = False;
	int speed=20;
	motor[rightF]=speed;
	motor[rightB]=speed;
	motor[leftF]=speed;
	motor[leftB]=speed;

	while (true){
	}
}
