#pragma config(Motor,  motorA,          claw,          tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          left,          tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          right,         tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

task main()
{
	int maxspeed;
	int dband=20;
	while (true)
	{
		getJoystickSettings(joystick)
		maxspeed=joystick.joy1_y1;
		nxtDisplayCenteredTextLine(3,"y1: %d",joystick.joy1_y1);
		nxtDisplayCenteredTextLine(4,"y2: %d",joystick.joy1_y2);
		nxtDisplayCenteredTextLine(5,"x1: %d",joystick.joy1_x1);


		if (abs(joystick.joy1_x1)<dband && abs(joystick.joy1_y1)<dband && abs(joystick.joy1_y2)<dband)
		{
			motor[left]=0;
			motor[right]=0;
			motor[claw]=0;
		}
		else
		{
			if (joystick.joy1_x1<0)
			{
				motor[left]=abs(maxspeed-joystick.joy1_x1);
				motor[right]=maxspeed;
			}
			if (joystick.joy1_x1>0)
			{
				motor[right]=abs(maxspeed-joystick.joy1_x1);
				motor[left]=maxspeed;
			}

			motor[claw]=joystick.joy1_y2;
		}
	}
}
