#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,          liftA,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          liftB,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     rightF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     rightB,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     leftF,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     leftB,         tmotorTetrix, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "Transfer2.0.c"
#include "JoystickDriver.c"

#define debug 1

// Comment one out:
#define properJoysticks 1 // actual joysticks -  Logitech Attack 3
//#define logitechDualShocks 1 // standard joysticks - Logitech Dual Shocks

task main()
{
	nMotorEncoder[liftA]=0;
	nMotorEncoder[liftB]=0;
	float joy_1y1;
	float joy_2y1;
	float joy_1x2;
	float joy_2x2;
	int dband=15;
	int liftLevels[2]={0, 2450};
	int encoderAverage;
	int armMovement=0;//0 = stopped, 1 = down, 2 = up
	int joyButtons1;
	int joyButtons2;
	int armSpeed;
	int driveSpeedLeft;
	int driveSpeedRight;

#ifdef properJoysticks
	int liftUpButton = 1;
	int liftDownButton = 1;
#elif defined(logitechDualShocks)
	float armGainSlow = 0.25;
	float armGainFast = 2.;
	float armGain = armGainFast;
	float driveGainSlow = 0.5;
	float driveGainFast = 1.;
	float driveGain = driveGainFast;
	int gainButton = 32;
#endif


	while (true){
		getJoystickSettings(joystick);
		joyButtons1=joystick.joy1_Buttons;
		joyButtons2=joystick.joy2_Buttons;

#ifdef properJoysticks
		joy_1x2 = (float)((joystick.joy1_x2*-1)+128) * 2./256.; // Drive Speed Multiplyer
		joy_2x2 = (float)((joystick.joy2_x2*-1)+128) * 100./256.; // Arm Speed
		joy_1y1 = transfer_J_To_M(joystick.joy1_y1, dband, joy_1x2); // Driver Right
		joy_2y1 = transfer_J_To_M(joystick.joy2_y1, dband, joy_1x2); // Driver Left

		if (joyButtons2 == liftUpButton){
			armSpeed = round(joy_2x2);
			armMovement = 2;
#if debug
			writeDebugStreamLine("arm up");
#endif
		}
		else if (joyButtons1 == liftDownButton){
			armSpeed = round(joy_2x2 * -1);
			armMovement = 1;
#if debug
			writeDebugStreamLine("arm down");
#endif
		}
		else {
			armMovement = 0;
			armSpeed = 0;
		}

		driveSpeedLeft = round(joy_1y1);
		driveSpeedRight = round(joy_2y1);

#elif defined(logitechDualShocks)
		if (joyButtons1==gainButton){	//drive gain
			driveGain = driveGainSlow;
		}
		else{
			driveGain = driveGainFast;
		}

		if (joyButtons2==gainButton){	//arm gain
			armGain = armGainSlow;
#if debug
			writeDebugStreamLine("arm slow");
#endif
		}
		else{
			armGain = armGainFast;
		}
		joy_1y1=transfer_J_To_M(joystick.joy1_y1, dband, driveGain * 150./300.);//Driver Joy
		joy_1y2=transfer_J_To_M(joystick.joy1_y2, dband, driveGain * 150./300.);
		joy_2y1=transfer_J_To_M(joystick.joy2_y1, dband, armGain * 100./128.);//Gunner Joy - Arm
		driveSpeedLeft = joy_1y1;
		driveSpeedRight = joy_1y2;
		armSpeed = joy_2y1;

		if (joy_2y1>0){//arm move up
			armMovement = 2;
		}
		else if (joy_2y1<0){//arm move down
			armMovement = 1;
		}
		else{//arm stopped
			armMovement = 0;
		}
#endif

		encoderAverage=(nMotorEncoder[liftA]+nMotorEncoder[liftB])/2; // arm encoder average between both motors


		//joy_2y2=transfer_J_To_M(joystick.joy2_y2, dband, 100./128.);
		//DRIVER//
		motor[leftF]=driveSpeedLeft;
		motor[leftB]=driveSpeedLeft;
		motor[rightF]=driveSpeedRight;
		motor[rightB]=driveSpeedRight;

		//Gunner//
		if (
			(encoderAverage<liftLevels[0] && armMovement == 1)// below lowest and going down
		|| (encoderAverage>liftLevels[sizeof(liftLevels)/sizeof(int)-1] && armMovement == 2) //above highest and going up
		|| armMovement == 0)//not moving
		{
			motor[liftA]=0;
			motor[liftB]=0;
#if debug
			writeDebugStreamLine("shouldn't move arm - dead banded or not being used");
#endif
		}
		else{
			// above lowest level and below highest level
			motor[liftA]=armSpeed;
			motor[liftB]=armSpeed;
		}
	}
}
