#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,          dispense,      tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     rightF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     rightB,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     leftF,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     leftB,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     motorH,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     lift,          tmotorTetrix, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "Transfer2.0.c"
#include "JoystickDriver.c"

//Timers used: T1 (stopping multi-dispsense)
#define debug 0

#if 1==0
#define properJoysticks 1 // actual joysticks -  Logitech Attack 3
#else
#define logitechDualShocks 1 // standard joysticks - Logitech Dual Shocks
#endif

task main()
{
	clearTimer(T1);
	nMotorEncoder[lift]=0;

	float joy_1y1;
	float joy_2y1;
	float joy_1y2;
	float joy_1x2;
	float joy_2x2;
	int dband=15;
	int liftLevels[2]={0, 12000};
	int encoderValue;
	int armMovement=0;//0 = stopped, 1 = down, 2 = up
	int joyButtons1;
	int joyButtons2;
	int armSpeed;
	int driveSpeedLeft;
	int driveSpeedRight;
	int initDispenseRotate=185;
	int dispenseRotate=60;
	int dispenseSpeed=15;
	int dispenseWait = 500; //ms

//Controller Type Param Setup
#ifdef properJoysticks
	//---Buttons---
	//int dispenseButton //<- figure out what to set
	int liftUpButton = 1;
	int liftDownButton = 1;
#elif defined(logitechDualShocks)
	float armGainSlow = 0.25;
	float armGainFast = 0.5;
	float armGain = armGainFast;
	float driveGainSlow = 0.5;
	float driveGainFast = 2;
	float driveGain = driveGainFast;

	//---Buttons---
	int dispenseButton = 2;
	int gainButton = 32;
#endif

// ----INIT Actions ----
motor[dispense]=0;
nMotorEncoderTarget[dispense]=initDispenseRotate;
motor[dispense]=dispenseSpeed;
while (nMotorRunState[dispense]==runStateIdle) {}

	while (true){
		encoderValue=(nMotorEncoder[lift]); // arm encoder average between both motors
		getJoystickSettings(joystick);
		joyButtons1=joystick.joy1_Buttons;
		joyButtons2=joystick.joy2_Buttons;

#if defined(properJoysticks)
		joy_1x2 = (float)((joystick.joy1_x2*-1)+128) * 2./256.; // Drive Speed Multiplyer
		joy_2x2 = (float)((joystick.joy2_x2*-1)+128) * 100./256.; // Arm Speed
		joy_1y1 = transfer_J_To_M(joystick.joy1_y1, dband, joy_1x2); // Driver Right
		joy_2y1 = transfer_J_To_M(joystick.joy2_y1, dband, joy_1x2); // Driver Left


		if (joyButtons2 == liftUpButton){
			armSpeed = round(joy_2x2);
			armMovement = 2;
#if debug
			writeDebugStreamLine("arm up");
#endif
		}
		else if (joyButtons1 == liftDownButton){
			armSpeed = round(joy_2x2 * -1);
			armMovement = 1;
#if debug
			writeDebugStreamLine("arm down");
#endif
		}
		else {
			armMovement = 0;
			armSpeed = 0;
		}

		driveSpeedLeft = round(joy_1y1);
		driveSpeedRight = round(joy_2y1);

#elif defined(logitechDualShocks)
		if (joyButtons1==gainButton){	//drive gain
			driveGain = driveGainSlow;
		}
		else{
			driveGain = driveGainFast;
		}

		if (joyButtons2==gainButton){	//arm gain
			armGain = armGainSlow;
#if debug
			writeDebugStreamLine("arm slow");
#endif
		}
		else{
			armGain = armGainFast;
		}
		joy_1y1=transfer_J_To_M(joystick.joy1_y1, dband, driveGain * 150./300.);//Driver Joy
		joy_1y2=transfer_J_To_M(joystick.joy1_y2, dband, driveGain * 150./300.);
		joy_2y1=transfer_J_To_M(joystick.joy2_y1, dband, armGain * 100./128.);//Gunner Joy - Arm
		driveSpeedLeft = round(joy_1y1);
		driveSpeedRight = round(joy_1y2);
		armSpeed = round(joy_2y1);
		if (driveSpeedLeft>100){
			driveSpeedLeft=100;
		}
		if (driveSpeedRight>100){
			driveSpeedRight=100;
		}
		if (armSpeed>100){
			armSpeed = 100;
		}

		if (joy_2y1>0){//arm move up
			armMovement = 2;
		}
		else if (joy_2y1<0){//arm move down
			armMovement = 1;
		}
		else{//arm stopped
			armMovement = 0;
		}
#endif

		//Universal Button Actions
		//Driver Buttons

		//Gunner Buttons
		if (joyButtons2==dispenseButton && nMotorRunState[dispense]!=runStateRunning && time1[T1]>dispenseWait){
			clearTimer(T1);
			motor[dispense]=0;
			nMotorEncoderTarget[dispense]=dispenseRotate;
			motor[dispense]=dispenseSpeed;
		}


		//Motor Speed Set
		//DRIVER//
		motor[leftF]=driveSpeedLeft;
		motor[leftB]=driveSpeedLeft;
		motor[rightF]=driveSpeedRight;
		motor[rightB]=driveSpeedRight;

		//Gunner//
		if (
			(encoderValue<=liftLevels[0] && armMovement == 1)// below lowest and going down
		|| (encoderValue>liftLevels[sizeof(liftLevels)/sizeof(int)-1] && armMovement == 2) //above highest and going up
		|| armMovement == 0)//not moving
		{
			motor[lift]=0;
#if debug
			writeDebugStreamLine("shouldn't move arm - dead banded or not being used");
#endif
		}
		else{
			// above lowest level and below highest level
			motor[lift]=armSpeed;
		}
	}
}
