#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     IR,             sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S3,     light,          sensorLightInactive)
#pragma config(Motor,  mtr_S1_C1_1,     left,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     right,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,      ,             tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,      ,             tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     arm1,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     arm2,          tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

float joyslope=(float)100/128;
	int dband=30; //deadband
	int joy_1y1;
	int joy_1y2;
	int joy_1x1;
	int joy_1x2;
	int tophat;
	int liftState=0;//make sure grabber is on ground level
	int maxLiftRev=0; //PLZ CHANGE
	int liftSpeed=50;
	int h0=0//height one
	int h1=0//height two PLZ CHANGE
	int h2=0//height three PLZ CHANGE

int transfer_J_To_M(int joy,float slope,int dead) // joy = joy input, dead = dead band, slope = max motor output/max joy input - in this case 100/128
{
	int y;
	if (abs(joy)<dead)
		y=0;
	else
		y=slope*((float)joy-(float)dead*sgn(joy));

	return y;
}

int liftHeight(int state, int tophat)
{
	int levels=1;
	int y=0;//return code
	if(tophat==0)//th is up
	{
		if (state<levels)//0 is ground
		{
			y=2; //code for up
		}
	}
	else if (tophat==4)
	{
		if (state<0)//lowest level
		{
			y=1;//code for down
		}
	}
	return y;
}

liftHights(int state, int dir)//state is level of lift before movement, dir is 1(down) or 2(up)
{
	int firstpos;
	if (state==0)
	{
		firstpos=h0;
		secondpos=h1;
	}
	else if ()
	int secpos;
}

task main()
{
	/*
	float joyslope=(float)100/128;
	int dband=30; //deadband
	int joy_1y1;
	int joy_1y2;
	int joy_1x1;
	int joy_1x2;
	int tophat;
	int hightState=0;//make sure grabber is on ground level
	int maxLiftRev=0; //PLZ CHANGE
	*/

	while (true)
	{
		getJoystickSettings(joystick);

		joy_1y1=transfer_J_To_M(joystick.joy1_y1, joyslope, dband); //left (front,back)
		joy_1y2=transfer_J_To_M(joystick.joy1_y2, joyslope, dband); //OVERIDE- up down
		joy_1x1=transfer_J_To_M(joystick.joy1_x1, joyslope, dband); //NIU- NOT IN USE
		joy_1x2=transfer_J_To_M(joystick.joy1_x2, joyslope, dband); //
		tophat=joystick.joy1_TopHat;
		/*
		if (joystick.joy1_TopHat==0)
		{
			if ()
			tophat=2; //2 code for up
		}
		else if (joystick.joy1_TopHat==4)
		{
			tophat=joy_1y2; //4 code for down
		}
		else
		{
			tophat=0;
		}
		*/

		if (liftHeight(liftstate, tophat)==2);
		{
			motor[]
		}


		motor[left] = (joy_1x1 + joy_1y1) / 2;
		motor[right] = (joy_1x1 - joy_1y1) / 2;

		if (joy_1y2==0)
		{
			//if ()
		}
		else
		{
		motor[arm1]=joy_1y2;
		motor[arm1]=joy_1y2;
		}
	}
}
