#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CHiTechnicCompass)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, PIDControl, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     FRight,        tmotorTetrix, PIDControl, reversed, driveRight)
#pragma config(Motor,  mtr_S1_C2_2,     BRight,        tmotorTetrix, PIDControl, reversed, driveRight)
#pragma config(Motor,  mtr_S1_C3_1,     FLeft,         tmotorTetrix, PIDControl, driveLeft)
#pragma config(Motor,  mtr_S1_C3_2,     BLeft,         tmotorTetrix, PIDControl, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

int transfer_J_To_M(int joy,float slope,int dead) // joy = joy input, dead = dead band, slope = max motor output/max joy input - in this case 100/128
{
	int y;
	if (abs(joy)<dead)
		y=0;
	else
		y=slope*((float)joy-(float)dead*sgn(joy));

	return y;
}

task main()
{
	/*Motor map:

	Motor Controller 1 = arm motors(not called in)
	Motor Controller 2 = left motor 1 & 2, spliced
	                     left motor 3
	Motor Controller 3 = right motor 1 & 2, spliced
	                     right motor 3*/

	int dband = 10;

	int joy_1y1=transfer_J_To_M(joystick.joy1_y1,100/128,dband);
	int joy_1y2=transfer_J_To_M(joystick.joy1_y2,100/128,dband);
	while (true)
	{
		getJoystickSettings(joystick);
		joy_1y1=transfer_J_To_M(joystick.joy1_y1,100/128,dband);
		joy_1y2=transfer_J_To_M(joystick.joy1_y2,100/128,dband);

		nxtDisplayCenteredBigTextLine(3,"%d",joy_1y1);
		motor[FLeft]=joy_1y1;
		motor[BLeft]=joy_1y1;
		motor[FRight]=joy_1y2;
		motor[BRight]=joy_1y2;
	}
}
