#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,          gripper,       tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     right,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     left,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     arm,           tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

int transfer_J_To_M(int joy,float slope,int dead) // joy = joy input, dead = dead band, slope = max motor output/max joy input - in this case 128/100
{
	int y;
	if (abs(joy)<dead)
		y=0;
	else
		y=slope*((float)joy-(float)dead*sgn(joy));

	return y;
}

task main()
{
	int dband=30;
	float alpha;
	int joy_x1,joy_x2,joy_y1,joy_y2;

	while (true)
	{
		getJoystickSettings(joystick);
		// Deadband 20, Slope is (motormax=100/(joymax=128-deadband))
		joy_y1 = transfer_J_To_M(joystick.joy1_x1,-(128.-dband)/98.,dband);
		joy_x1 = transfer_J_To_M(joystick.joy1_y1,-(128.-dband)/98.,dband);

		joy_x2 = transfer_J_To_M(joystick.joy1_x2,-1./4.,dband);
		// Joy Left = close arm, joy right = open arm
		joy_y2 = transfer_J_To_M(joystick.joy1_y2,-1./4.,dband);
		// Forward moves arm down, Backwards moves arm up

		if (joy_x1==0) // Straight forward or back
		{
			motor[left]=joy_y1;
			motor[right]=joy_y1;
		}
		else if (joy_y1==0) // Tank turn proportional to left/right deflection
		{
			motor[left]= joy_x1;
			motor[right]= -joy_x1;
		}
		else
		// Steer by slowing track that is in direction we want to trun towards
		// Fast track moves with value of joy_y1
		// Slower track moves with alpha * joy_y1
		// alpha = 1-abs(joy_x1)/100. , alpha is in range 0 and 1
		{
			alpha = (100.-abs((float)joy_x1))/100.; // assume joy_x1 in range -100 to +100
			if (alpha>1.) alpha=1.; // Keep alpha in range 0 to 1
			if (alpha<0.) alpha=0.;

			if (joy_x1>0) //turing right, slow right wheel
			{
				motor[left]= joy_y1;
				motor[right]= alpha*joy_y1;
			}
			else //turning left, slow left wheel
			{
				motor[left]= alpha*joy_y1;
				motor[right]= joy_y1;
			}
		}



			motor[arm]=(joy_y2);
			motor[gripper]=(joy_x2);
	}
}
