#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,          gripper,       tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     right,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     left,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     arm,           tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

task main()
{
	int maxspeed;
	int dband=30;
	float alpha;

	while (true)
	{
		getJoystickSettings(joystick);
		maxspeed=joystick.joy1_y1;
		/*
		if (abs(joystick.joy1_x1)<dband && abs(joystick.joy1_y1)<dband && abs(joystick.joy1_y2)<dband && abs(joystick.joy1_x2)<dband)
		{
			motor[left]=0;
			motor[right]=0;
			motor[arm]=0;
			motor[gripper]=0;
		}
		else
		{
			if (joystick.joy1_x1<0)
			{
				motor[left]=abs(maxspeed-joystick.joy1_x1);
				motor[right]=maxspeed;
			}
			if (joystick.joy1_x1>0)
			{
				motor[right]=abs(maxspeed-joystick.joy1_x1);
				motor[left]=maxspeed;
			}

			motor[arm]=joystick.joy1_y2;
			motor[gripper]=joystick.joy1_x2;
		}
		*/
		alpha=abs(joystick.joy1_x1)/abs(maxspeed); // alpha will be left as this if the "if" statement a few lines below is false

		if (abs(joystick.joy1_x1)>dband && abs(joystick.joy1_y1)>dband)
		{
			if (maxspeed<alpha) // Setting up the alpha, how much to slow down the motor on the side of the turn
			{
				alpha=1; // the wheel wont move at all
			}

			if (joystick.joy1_x1<0) //tilted to left
			{
				motor[left]=-1*(maxspeed-(maxspeed*alpha)); // reversed
				motor[right]=maxspeed;
			}
			else if (joystick.joy1_x1>0) // tilted to right
			{
				motor[right]=maxspeed-(maxspeed*alpha);
				motor[left]=-1*maxspeed; // reversed
			}
			else // full seam ahead
			{
				motor[right]=maxspeed;
				motor[left]=maxspeed;
			}
		}
		else
		{
			motor[left]=0;
			motor[right]=0;
		}

		if (abs(joystick.joy1_y2)>dband && abs(joystick.joy1_x2)>dband)
		{
			motor[arm]=(joystick.joy1_y2/4);
			motor[gripper]=(joystick.joy1_x2/4);
		}
		else
		{
			motor[arm]=0;
			motor[gripper]=0;
		}
	}
}
