#pragma config(Sensor, S1,     touchF,         sensorTouch)
#pragma config(Sensor, S2,     touchR,         sensorTouch)
#pragma config(Motor,  motorA,          motorL,        tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          motorR,        tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int maxspeed=80;
	while (true)
	{
		if (SensorValue[touchF]==1)
		{
			motor[motorR]=maxspeed;
			motor[motorL]=maxspeed;
		}
		else if (SensorValue[touchR]==1)
		{
			motor[motorR]=-1*maxspeed;
			motor[motorL]=-1*maxspeed;
		}
		else
		{
			motor[motorR]=0;
			motor[motorL]=0;
		}
	}
}
