#pragma config(Sensor, S1,     accel,          sensorI2CHiTechnicAccel)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "hitechnic-accelerometer.h"

task main()
{
	while (true){
		int sensorVal=SensorValue[accel];
		nxtDisplayCenteredBigTextLine(3,"%d",sensorVal);
	}
}
