#pragma config(Sensor, S2,     gyro,           sensorI2CHiTechnicGyro)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "hitechnic-accelerometer.h"

task main()
{
  int x;
  int y;
  int z;
  int advanced=true;
  while (true){
    int sensorVal=SensorValue[gyro];
    nxtDisplayCenteredBigTextLine(3,"%d", sensorVal);
  }
}
