#pragma config(Sensor, S2,     gyro,           sensorI2CHiTechnicGyro)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "hitechnic-accelerometer.h"

task main()
{
	int sensorVal;
	int average=0;
	int loopTimes = 0;
	int loopMax = 100;
	while (true){
		loopTimes = 0;
		average=0;
		while ( loopTimes++ < loopMax ){
			sensorVal=SensorValue[gyro];
			average=average+sensorVal;
		}

		nxtDisplayCenteredBigTextLine(6,"%d", (average/loopTimes));
		// nxtDisplayCenteredBigTextLine(3,"%d", sensorVal);
	}
}
