#pragma config(Sensor, S1,     MUX,            sensorI2CCustomFastSkipStates)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "hitechnic-sensormux.h"
#include "lego-ultrasound.h"

const tMUXSensor LEGOUS = msensor_S1_1;

task main()
{
	int dist = 0;

	while (){
		dist = USreadDist(LEGOUS);
		nxtDisplayCenteredBigTextLine(3,"%d",dist);
	}
}
