#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     rightF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     rightB,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     leftF,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     leftB,         tmotorTetrix, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "Transfer2.0.c"
#include "JoystickDriver.c"

task main()
{
	int joy_1y1;
	int joy_1y2;
	int dband=15;

	while (true){
		getJoystickSettings(joystick);
		joy_1y1=transfer_J_To_M(joystick.joy1_y1, dband, 150./300.);//Driver Joy
		joy_1y2=transfer_J_To_M(joystick.joy1_y2, dband, 150./300.);

		motor[leftF]=joy_1y1;
		motor[leftB]=joy_1y1;
		motor[rightF]=joy_1y2;
		motor[rightB]=joy_1y2;
	}
}
