#pragma config(Sensor, S3,     touch,          sensorTouch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (true){
	writeDebugStreamLine("%d",SensorValue[touch]);
	}
}
