#pragma config(Sensor, S1,     compass,        sensorI2CHiTechnicCompass)
#pragma config(Sensor, S4,     SMUX,           sensorI2CCustomFastSkipStates)
#pragma config(Motor,  motorA,          left,          tmotorNXT, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorB,          right,         tmotorNXT, PIDControl, driveRight, encoder)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//using updated versions of "wallfollow2.0.c" and "compassfollow2.0.c" -- has no motor limit

#include "wallfollow2.0.c"
#include "compassfollow2.0.c"
#include "mindsensors-motormux.h"
#include "hitechnic-sensormux.h"

void init(){
	//ENCODERS//
	nMotorEncoder[left]=0;
	nMotorEncoder[right]=0;

	//SOUND//
	nVolume = 2;
	bPlaySounds = true;
}

task main()
{
	//	int compOffSet=SensorValue[compass];
	//	int rotateAmount=20;//rotate amount in degrees for second part
	//	int rotateTarget=compOffSet;//for 2nd half
	int rotateTarget;

	//	int rotateSpeed=50;

	int fieldlength=176;//cm
	int failsafedis=600*(fieldlength/19);//600 on the motor encoder results in moving 19 cm
	int dropdis=10;//cm
	int walldis=20;//cm
	int speed=50;
	int rotateSpeed;
	bool sonarStop;
	int timeSensorEnable;
	int stopdis;
	tMotor leftSide[1]={left};
	tMotor rightSide[1]={right};
	tMUXmotor leftSideMUX[1]={mmotor_S1_2};
	tMUXmotor rightSideMUX[1]={mmotor_S1_1};

	tMUXSensor rSonar=msensor_S1_3;
	tMUXSensor fSonar=msensor_S1_1;
	tMUXSensor bSonar=msensor_S1_2;

	init();

	//START

	wallfollow(walldis,speed,dropdis,failsafedis,fSonar,rSonar,leftSide,rightSide,leftSideMUX,rightSideMUX);
	MSMMotor(mmotor_S1_1,0);
	MSMMotor(mmotor_S1_2,0);
	// ROTATE TO NEW BEARING ON SPOT

	rotateTarget=SensorValue[compass]+20;
	speed = 0;
	rotateSpeed=50;
	sonarStop = false;
	timeSensorEnable=300;//10 ms increments
	stopdis=50;

	compassfollow(speed,rotateSpeed,rotateTarget,timeSensorEnable,sonarStop,stopdis,compass,bSonar,rSonar,leftSide,rightSide,leftSideMUX,rightSideMUX);
	MSMMotor(mmotor_S1_1,0);
	MSMMotor(mmotor_S1_2,0);
	// THEN DRIVE ON SIMILAR BEARING UNTIL HITS WALL

	rotateTarget=rotateTarget-20;
	speed = 50;
	rotateSpeed=0;
	sonarStop = true;
	timeSensorEnable=300;//10 ms increments
	stopdis=50;

	compassfollow(speed,rotateSpeed,rotateTarget,timeSensorEnable,sonarStop,stopdis,compass,bSonar,rSonar,leftSide,rightSide,leftSideMUX,rightSideMUX);
	MSMMotor(mmotor_S1_1,0);
	MSMMotor(mmotor_S1_2,0);
}
