#pragma config(Sensor, S1,     accel,          sensorI2CCustom)
#pragma config(Motor,  motorA,          left,          tmotorNXT, PIDControl, reversed, driveLeft, encoder)
#pragma config(Motor,  motorB,          right,         tmotorNXT, PIDControl, reversed, driveRight, encoder)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//motor[left] is the master and the slave it motor[right]
#include "hitechnic-accelerometer.h"

//Timers Used: T1 (change Rate),
void init(){
	//Motors//
	nSyncedMotors = synchAB;
	nSyncedTurnRatio = 100;//the same as the master (100%)
}

task main()
{
	int accelOffSet = 20;
	int multiplyer = 8;
	int samplePeriod = 300;//msec
	int bigPushVal = 40;
	int speedDeadband=50;
	float fastGain=4;
	float normalGain=1;
	float gain=normalGain;
	float delta;
	int x;
	int y;
	int z;
	int motorOutput;

	HTACreadAllAxes(accel, x, y, z);
	int firstAcc=x;
	int secondAcc=x;

	init();
	ClearTimer(T1);
	wait1Msec(samplePeriod+5);
	while (true){
		wait1Msec(1);//keep the program from slowing down from so many loops
		HTACreadAllAxes(accel, x, y, z);
		delta = (x+accelOffSet);
		//delta = delta/20.;
		motorOutput = round(multiplyer*delta);

		/*
		if (time1[T1]>samplePeriod){
			ClearTimer(T1);
			secondAcc=x;

			if (secondAcc-firstAcc>bigPushVal && abs(x)>speedDeadband){
				gain=fastGain;
				nxtDisplayCenteredTextLine(7,"SPEED");
			}
			else{
				nxtDisplayCenteredTextLine(7,"SLOW");
				gain=normalGain;
			}
			firstAcc=x;
		}*/

		/*
		delta = (SensorValue[accel]);
		nxtDisplayCenteredBigTextLine(5,"%d",delta);
		delta = (delta+500 % 1000)-500;
		delta = delta/100.;*/
		nxtDisplayCenteredTextLine(2,"delta: %f",delta);
		nxtDisplayCenteredTextLine(5,"motorOutput: %d",motorOutput);
		nxtDisplayCenteredTextLine(6,"value: %d",x);

		motor[left] = round(multiplyer*delta*gain);
	}
}
