#pragma config(Sensor, S1,     accel,          sensorI2CHiTechnicAccel)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "hitechnic-accelerometer.h"

task main()
{
	while (true){
		delta = (SensorValue[accel]);
		delta = (delta+180 % 360)-180;
		delta = delta/100.;
	}
}
