#pragma config(Motor,  motorA,          motor1,        tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          motor2,        tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	bFloatDuringInactiveMotorPWM = true;
	int speed=100;
	float encoderAverage;
	motor[motorA]=speed;
	motor[motorB]=speed;
	while (true){
		encoderAverage=(nMotorEncoder[motor1]+nMotorEncoder[motor2])/2;
		writeDebugStreamLine("%f",encoderAverage);
	}
}
